# Generated by Django 5.1.3 on 2024-12-01 11:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_photos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photos'),
        ),
    ]
